[package]
name = "key_tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2_proofs.workspace = true
pairing_bn256 = { git = "https://github.com/lanbones/pairing.git" }
anyhow = "1.0.81"
pairing_ce = "0.24.2"
num-traits = "0.2.19"
once_cell = "1.19.0"
chksum-md5 = "0.0.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
byteorder = "1.5.0"
num-bigint = "0.4.6"

